name: 'Slack Notifier Actions'
description: 'your github notifications to slack, notifications customizer'
author: 'shzxcv'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bell'
  color: 'blue'
